### ISSUE TITLE
Need various --add-exports to have RangeSlider work in modularized project.

### ISSUE THREAD

**Issue by JonathanGiles** [controlsfx/controlsfx#1073]
**[Original report](https://bitbucket.org/controlsfx/controlsfx/issue/882) by Sebastien Kister (Bitbucket: [SebKister](https://bitbucket.org/SebKister), GitHub: [SebKister](https://github.com/SebKister)).**

----------------------------------------

I added a single RangeSlider control to a modularized Java project under Oracle JDK 10.0.2.
In order to run the application I had to add the following to the VM arguments:

--add-exports=javafx.base/com.sun.javafx.runtime=controlsfx
--add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=controlsfx
--add-exports=javafx.controls/com.sun.javafx.scene.control.inputmap=controlsfx
--add-exports=javafx.graphics/com.sun.javafx.scene.traversal=controlsfx

**Comment by MajeurAndroid** [comment]
I still have this issue with 11.0.1, any news ?

**Comment by abhinayagarwal** [comment]
As stated before, these JVM flags will be required until we get rid of the Behavior classes or internal API :(

We are making progress and we have removed dependency on a [few of these flags](https://github.com/controlsfx/controlsfx/compare/b9a3b1e..48e7773#diff-c197962302397baf3a4cc36463dce5ea) since the last release.

**Comment by Kscstg** [comment]
I am a rookie, I don't know how to add JVM parameters, can you help me?
![20201029094800](https://user-images.githubusercontent.com/63573861/97515557-3ea5ad00-19cc-11eb-8cba-6d828f933602.png)

**Comment by Kscstg** [comment]
![Uploading 20201029094800.png…]()

**Comment by LMonir** [comment]
Version 11.0.3 still the problem.

Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: superclass access check failed: class impl.org.controlsfx.behavior.RangeSliderBehavior (in module org.controlsfx.controls) cannot access class com.sun.javafx.scene.control.behavior.BehaviorBase (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to module org.controlsfx.controls

And the VM arguments doesn't work for Java 11.
Any solutions?
