### ISSUE TITLE
HiddenSidesPane stops working when the pinnedSide Property is set during Animation

### ISSUE THREAD

**Issue by wirew0rm** [controlsfx/controlsfx#1181]
Our application uses a HiddenSidePane to show a Toolbar and sets it to pinned when it is clicked.
This works really well, but we noticed, that clicking the toolbar (and therefore triggering a callback setting the pinnedSideProperty to the side the bar is shown in) while it its slideout animation is playing prevents the SidePane from ever being shown again.

This might also be loosely related to #891. While for us the pane does not collapse on every click or when hovering child nodes, it scrolls out when we click and therefore unpin the side. At this time, the cursor is obviously still in the toolbar area and the toolbar should not hide.

(As an aside,  is there some elegant way to stop the side pane from hiding while elements like dropdowns and menus, which are drawn outside of the side node are used? For now I set and unset the pinnedSide in the context menu's showing/hiding callbacks.)

As the hiddenSidePane behaviour might be version dependent, we are running on openjdk11.0.3 + openjfx12.0.2 + controlsfx 11.0.0.

**Comment by Maxoudela** [comment]
Can you provide an [short example](http://sscce.org/) of this issue?

Are you able to provide a pull request with a beginning of a solution so we can talk on the code?

Regarding your second question, I also experienced this issue and I basically created a `GlobalShowingProperty` that was concatenating all `showingProperty` of all my `MenuButtons`. When this property was set to true (one `menuButton` was interacted with) I also pinned a side in order for the toolbar not to be hidden. We could improve the HiddenSidePane so that if one item in the component is interacted with, the side should stay visible.

**Comment by wirew0rm** [comment]
I finally got my controlsfx with fxsampler working again and tried to reproduce in the demo there. When trying to find the issue, I realized, that there was actually a modified copy of the HiddenSidePane :neutral_face: 

We also did some experimentation on preventing the sidebar from hiding and added some code to our custom version: https://github.com/GSI-CS-CO/chart-fx/blob/ce374b438decaa1f346d35319dbe3fb41bd40658/chartfx-chart/src/main/java/de/gsi/chart/ui/HiddenSidesPaneSkin.java#L186-L208

If there was a reliable way to get all the child elements, this would be a lot easier, because the Reflection would not be needed. Alternatively we could check for Menu, MenuButton, ChoiceBox  and ComboBox manually, but this would make it impossible to use custom controls that do not extend these.

We also invoke hide() on the menus before collapsing the side pane, because it looks strange if the pane rolls out and only then the menus are destroyed.
