### ISSUE TITLE
ReflectionUtils Illegal Reflective Access Operation

### ISSUE THREAD

**Issue by DSheirer** [controlsfx/controlsfx#1234]
OS: Linux Kubuntu 16.04
JDK: Bellsoft OpenJDK 13.0.1
Release: ControlsFX 11.0.1

Simply instantiating the ListSelectionView and adding the control to a titled pane produces the following warning:
 
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by impl.org.controlsfx.ReflectionUtils (file:/home/denny/.gradle/caches/modules-2/files-2.1/org.controlsfx/controlsfx/11.0.1/66df6f3526734d37226ea36cc32940083e6fb697/controlsfx-11.0.1.jar) to method com.sun.javafx.css.StyleManager.getInstance()
WARNING: Please consider reporting this to the maintainers of impl.org.controlsfx.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

**Comment by danielpeintner** [comment]
I believe this is a known issue. There are still some of these _extensions_ needed

see https://github.com/controlsfx/controlsfx/blob/9.0.0/build.gradle in branch `9.0.0`

**Comment by nicolabeghin** [comment]
thanks @danielpeintner not sure how to get around this/remove the warning when running the app? 
If I understand correctly the incriminated line is https://github.com/controlsfx/controlsfx/blob/9.0.0/build.gradle#L6

**Comment by danielpeintner** [comment]
I am not sure whether the warnings themselves can be removed/suppressed. There are some hints [here](https://stackoverflow.com/questions/46454995/how-to-hide-warning-illegal-reflective-access-in-java-9-without-jvm-argument) but I did not look into that. The ultimate goal is to get rid of all illegal accesses step by step anyway.

Personally when running user interface apps like ControlsFX I do not bother so much when it comes to the warnings since I seldomly start them in the command shell.

**Comment by abhinayagarwal** [comment]
This warning is thrown by the JVM when ControlsFX tries to reflectively access few class/methods. Currently, there is no workaround. There are ways on the internet to hide these warnings.
