### ISSUE TITLE
Version Checker Seems to Think Java Version is Wrong

### ISSUE THREAD

**Issue by snorhax** [controlsfx/controlsfx#1240]
I get 

> java.lang.RuntimeException: ControlsFX Error: ControlsFX 11.0.1 requires at least Java Version 9

When I run `doVersionCheck()` from VersionChecker, or I try to use SegmentedButton. My use of ControlsFX is sparse in my project; I only use SegmentedButton, ToggleSwitch, Glyphs, and  AutoCompletionBindings. Seems to only trigger when using the SegmentedButton.

What's confusing me is that I'm targeting OpenJDK 11, my OpenJFX version is set to 13-ea+8, and when I call `System.getProperty("javafx.version")` (which is what VersionChecker does) I get 10.0.2-internal. I want to say this an issue but I haven't seen anyone else complain about the version checker recently. Is the problem on my end?

Also: I'm also getting `WARNING: An illegal reflective access operation has occurred` when I start my application if that helps at all.

**Comment by Speljohan** [comment]
I'm having the same issue, would be great if there is a solution for this.

**Comment by Maxoudela** [comment]
If you look at the file here : https://github.com/controlsfx/controlsfx/blob/9.0.0/controlsfx-build.properties

You see that the minimum version needed is `11.0.2`. (For the release it should be `11.0.1`). So the bug is that the name of the Java version is wrong. It should be "Java Version 11" instead of "Java version 9".

If you have `10.0.2-internal` when doing `System.getProperty("javafx.version")`, it surely means that you are not using OpenJFX 13. Are you sure you are using it?

**Comment by snorhax** [comment]
I've actually upgraded to OpenJFX 14 recently and the problem still occurs. I am using Maven for dependencies and I've even made an effort to look through my local .m2 repository and delete any OpenJFX dependencies lower than 11.0.2. The problem still persists, and I'm not sure what else I can do.

**Comment by abhinayagarwal** [comment]
@snorhax @Speljohan Is it possible for anyone of you to post a [SSCCE](http://www.sscce.org/) which can reproduce the issue?

**Comment by ckosmowski** [comment]
> If you have `10.0.2-internal` when doing `System.getProperty("javafx.version")`, it surely means that you are not using OpenJFX 13. Are you sure you are using it?

I do have the same problem i am using openjfx 11.0.2 and the system property is reporting 10.0.2-internal, so version check fails. The "at least java 9" message makes it even more confusing.

However in any case it would really be useful if the VersionChecker can be disabled, because it obviously makes false assumptions about the environment of the developer. It might have to do with the way javafx dependecy is imported (i use a gradle plugin for that).

**Comment by abhinayagarwal** [comment]
VersionChecker seems to be an unwanted class. I will see if the class can be removed.
