### ISSUE TITLE
Github main page suggests version 9.0.0 for JavaFX 9+, but doesn't support 11

### ISSUE THREAD

**Issue by cmhulbert** [controlsfx/controlsfx#1279]
When trying to use version 9.0.0 for a javafx 11 project, the module org.controlsfx.controls is not provided. It would be nice if documentation was updated to show that using 11.0.1 was all I needed to do

**Comment by boessu** [comment]
May I ask the specific issue here?
The maven central lists V11.0.1. Of course there are some 9+ pitfalls because of Java Platform Module System, but that's well documented in  the Wiki (https://github.com/controlsfx/controlsfx/wiki/Using-ControlsFX-with-JDK-9-and-above). As far as I know, there are even features which doesn't work actually because of this, but that needs some search... 
(I personally still use JDK 8, as we've still installed that runtime on the clients. Although that will change and then I'll run into the same problem ;-)
So is there a problem that (parts of) controlsfx doesn't work or is this a "documentation only" problem on the title page?

**Comment by abhinayagarwal** [comment]
On the Github README, `9.0.0` is referred to the branch and not any particular version of the project itself.

**Comment by cmhulbert** [comment]
I suspect it's a documentation only issue.

My specific issue is that I was trying to using controlsfx with a java 11 modular project, but I was following the instruction on the github readme. This led me to use version 9.0.0, which wasn't working when trying to compile. This turned out to be that I was trying to `requires org.controlsfx.controls;` but that module is not provided by version 9.0.0.0. This caused me to look around for the issue, and ultimately found out that there was an 11.0.0 version available, and that one does provide that module. 

I just opened this so that if any other have this issue, they'll see this and save time by just using 11.0.0.0, or ideally the README on github would suggest 11.0.0.0 for Java 11, rather than 9.0.0.0 for 9+
